kind: pipeline
name: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/docker/cli

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.21-loongnix
    environment:
      VERSION: 26.1.5-beagle
      PLATFORM: Beagle Cloud Team 2023-2028
    commands:
      - bash .beagle/build.sh

  - name: buildx-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.16.2-amd64
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-amd64

  - name: buildx-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.16.2-arm64
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-arm64

  - name: buildx-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.16.2-ppc64le
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-ppc64le

  - name: buildx-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.16.2-mips64le
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-mips64le

  - name: buildx-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.16.2-loong64
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-loong64

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/docker-cli
      version: v26.1.5
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      repo: wod/docker-cli
      version: v26.1.5
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-ppc64le
      repo: wod/docker-cli
      version: v26.1.5
      channel: ppc64le
      args: "TARGETOS=linux,TARGETARCH=ppc64le"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-mips64le
      repo: wod/docker-cli
      version: v26.1.5
      channel: mips64le
      args: "TARGETOS=linux,TARGETARCH=mips64le"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/docker-cli
      version: v26.1.5
      channel: loong64
      args: "TARGETOS=linux,TARGETARCH=loong64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
