kind: pipeline
name: docker

trigger:
  branch:
    - release-v27

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  path: /go/src/github.com/docker/cli

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
      endpoint: https://cache.ali.wodcloud.com
      access_key:
        from_secret: S3_ACCESS_KEY_ALIYUN
      secret_key:
        from_secret: S3_SECRET_KEY_ALIYUN

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.23
    environment:
      VERSION: 27.4.0-beagle
      PLATFORM: Beagle Cloud Team 2023-2028
    commands:
      - bash .beagle/build.sh

  - name: golang-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.22-loongnix
    environment:
      VERSION: 27.4.0-beagle
      PLATFORM: Beagle Cloud Team 2023-2028
    commands:
      - bash .beagle/build-loong64.sh

  - name: buildx-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.19.2-amd64
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-amd64

  - name: buildx-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.19.2-arm64
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-arm64

  - name: buildx-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/docker-buildx:v0.19.2-loong64
    commands:
      - mkdir -p build
      - cp /usr/libexec/docker/cli-plugins/docker-buildx build/docker-buildx-linux-loong64

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/docker-cli
      version: v27.4.0
      channel: amd64
      args: "TARGETOS=linux,TARGETARCH=amd64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-arm64
      repo: wod/docker-cli
      version: v27.4.0
      channel: arm64
      args: "TARGETOS=linux,TARGETARCH=arm64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-loong64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/build.Dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3-amd64
      repo: wod/docker-cli
      version: v27.4.0
      channel: loong64
      args: "TARGETOS=linux,TARGETARCH=loong64"
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_ACCESS_KEY_ALIYUN
get:
  name: S3_ACCESS_KEY_ALIYUN
  path: devops-secrets

---
kind: secret
name: S3_SECRET_KEY_ALIYUN
get:
  name: S3_SECRET_KEY_ALIYUN
  path: devops-secrets
